# coding:utf-8
from selenium import webdriver
from time import sleep
driver = webdriver.Chrome()
driver.get("http://192.168.0.111/crm/index.php?m=user&a=login")
driver.find_element_by_name("name").send_keys("zhangqi")
driver.find_element_by_name("password").send_keys("zhangqi123")
driver.find_element_by_name("submit").click()
sleep(1)
driver.find_element_by_xpath("/html/body/div[1]/div/div/div[2]/ul[1]/li[3]/a").click()
driver.find_element_by_xpath("/html/body/div[5]/div[2]/div[1]/div/a").click()
driver.find_element_by_xpath('//*[@id="owner_name"]').send_keys("zhangqi")
sleep(2)
driver.find_element_by_xpath('//*[@id="customer_name"]').click()
sleep(1)
driver.find_element_by_xpath('//*[@id="datas"]/tr[3]/td[1]/input[1]').click()
sleep(1)
driver.find_element_by_xpath('/html/body/div[10]/div[3]/div/button[1]/span').click()
driver.find_element_by_xpath('//*[@id="total_price"]').send_keys("200000")
sleep(1)
driver.find_element_by_xpath('//*[@id="name"]').send_keys(u"举办生日演唱会")
driver.find_element_by_xpath('//*[@id="contacts_name"]').send_keys("qiqi")
sleep(1)
driver.find_element_by_xpath('//*[@id="form1"]/table/tbody/tr[5]/td[2]/select[1]/option[20]').click()
driver.find_element_by_xpath('//*[@id="form1"]/table/tbody/tr[5]/td[2]/select[2]/option[4]').click()
driver.find_element_by_xpath('//*[@id="form1"]/table/tbody/tr[5]/td[2]/select[3]/option[6]').click()
driver.find_element_by_xpath('//*[@id="form1"]/table/tbody/tr[5]/td[2]/input').send_keys(u"坂田街道")
driver.find_element_by_xpath('//*[@id="type"]').send_keys(u"新业务")
driver.find_element_by_xpath('//*[@id="status_id"]').send_keys(u"意向客户")
sleep(1)
driver.find_element_by_xpath('//*[@id="origin"]/option[3]').click()
driver.find_element_by_xpath('//*[@id="gain_rate"]').send_keys("99")
driver.find_element_by_xpath('//*[@id="estimate_price"]').send_keys("200000")
driver.find_element_by_xpath('//*[@id="nextstep_time"]').send_keys("2018-10-28 19:30")
sleep(1)
driver.find_element_by_xpath('//*[@id="nextstep"]').send_keys(u"粉丝福利相关")
driver.find_element_by_xpath('//*[@id="form1"]').send_keys()